url: "https://devevolved.github.io"
title: DevEvolved
logo: /images/logo-transparent-back-small-png.png

github:
  repo: https://github.com/devevolved/devevolved.github.io
  feedback: https://github.com/devevolved/feedback

sass:
    style: compressed

gems:
  - jekyll-feed
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Output options (more information on Jekyll's site)
encoding: UTF-8
timezone: America/New_York
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
paginate: 5
kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
      banner: false # do not include a banner image
  -
    scope:
      path: "" # all files
    values:
      layout: "default"
      show-avatar: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      nav-include: true  # include in header nav

# SEO configuration


twitter:
  username: devevolvedHQ
  card: summary

social:
  links:
    - https://twitter.com/devevolvedHQ
    - https://www.facebook.com/devevolved
    - https://www.linkedin.com/company/devevolved
    - https://github.com/devevolved

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
